webtool/ugahash/hasher/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^/hashmapped/$', views.hashmapped, name='hashmapped'),
    #url(r'^sequence/', views.sequence, name='sequence'),
    url(r'^sequence/(?P<hash_id>.*)$', views.sequence, name='sequence'),
    url(r'^json/(?P<hash_id>.*)$', views.externalids, name='externalids'),
    url(r'^$', views.index, name='index'),
]

webtool/ugahash/help/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),

]

webtool/ugahash/ugahash/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    #url(r'^help/', TemplateView.as_view(template_name='ugahash/index.html'), name='help'),
    url(r'^help/',     include('help.urls'), name='help'),
    url(r'^linkerror/',     TemplateView.as_view(template_name='ugahash/nolink.html'), name='home'),
    url(r'^hash/',     include('hasher.urls')),
    url(r'^idsearch/', include('idsearch.urls')),
    url(r'^admin/',    include(admin.site.urls)),
    url(r'^', TemplateView.as_view(template_name='ugahash/index.html'), name='home'),
]

webtool/ugahash/hasher/models.py
from django.db import models
"""
source_base_url = models.CharField(max_length=400) #http://www.noncode.org/show_gene.php?id=NONHSAG000001
gene_url = models.CharField(max_length=400) #http://www.noncode.org/show_gene.php?id=NONHSAG000001
transcript_url = models.CharField(max_length=400) #http://www.noncode.org/show_gene.php?id=NONHSAG000001
exon_url = models.CharField(max_length=400) #http://www.noncode.org/show_gene.php?id=NONHSAG000001
"""


class SequenceSet(models.Model):
    source_version_id = models.CharField(max_length=80, primary_key=True)
    source = models.CharField(max_length=80)
    version = models.CharField(max_length=80)
    tax_id = models.CharField(max_length=80)
    assembly = models.CharField(max_length=80)
    link = models.CharField(max_length=400)

    class Meta:
        unique_together = ('source', 'version', 'tax_id', )


class Sequence(models.Model):
    """
    ForeignKey.on_delete
    When an object referenced by a ForeignKey is deleted, Django by default emulates the behavior of the SQL
    constraint ON DELETE CASCADE and also deletes the object containing the ForeignKey. This behavior can be
    overridden by specifying the on_delete argument. For example, if you have a nullable ForeignKey
    and you want it to be set null when the referenced object is deleted:
    """
    #These four key feild together should be unique
    hash_id = models.CharField(max_length=80, primary_key=True)
    tax_id = models.CharField(max_length=80)
    seq_type = models.CharField(max_length=80)
    assembly = models.CharField(max_length=80)
    chromosome = models.CharField(max_length=80)
    strand = models.CharField(max_length=1) #(+|-|.)
    start = models.IntegerField()  # 3063334
    stop = models.IntegerField()  # 3064403

    seqsetrels = models.ManyToManyField(SequenceSet,
                                        through='SequenceSetSequenceRelation',
                                        through_fields=('hash_id', 'source_version_id',))

    #class Meta:
    #    unique_together = ('hash_id', 'assembly', 'chromosome', 'strand', 'start', 'stop')
    #def __unicode__(self):
    #    return unicode("\t".join([self.original_id, self.chromosome, str(self.start)]))


class SequenceSetSequenceRelation(models.Model):
    """
    ForeignKey.on_delete
    When an object referenced by a ForeignKey is deleted, Django by default emulates the behavior of the SQL
    constraint ON DELETE CASCADE and also deletes the object containing the ForeignKey. This behavior can be
    overridden by specifying the on_delete argument. For example, if you have a nullable ForeignKey
    and you want it to be set null when the referenced object is deleted:
    """
    #These four key feild together should be unique
    #id = models.AutoField(primary_key=True)
    source_version_id = models.ForeignKey(SequenceSet, on_delete=models.CASCADE)
    hash_id = models.ForeignKey(Sequence, on_delete=models.CASCADE)
    original_id = models.CharField(max_length=80)

    class Meta:
        unique_together = ('source_version_id', 'hash_id')


class ParentChildSeqRelations(models.Model):
    """
    ForeignKey.on_delete
    When an object referenced by a ForeignKey is deleted, Django by default emulates the behavior of the SQL
    constraint ON DELETE CASCADE and also deletes the object containing the ForeignKey. This behavior can be
    overridden by specifying the on_delete argument. For example, if you have a nullable ForeignKey
    and you want it to be set null when the referenced object is deleted:
    """
    #These four key feild together should be unique
    id = models.AutoField(primary_key=True)
    parent_hash_id = models.ForeignKey(Sequence, related_name='parent_hash_id')  #models.CharField(max_length=80)
    parent_type = models.CharField(max_length=80)
    child_hash_id = models.ForeignKey(Sequence, related_name='child_hash_id')
    child_type = models.CharField(max_length=80)
    rank = models.IntegerField()

    class Meta:
        unique_together = ('parent_hash_id', 'parent_type', 'child_hash_id', 'child_type', 'rank')

webtool/ugahash/hasher/forms.py
from django import forms
from .models import SequenceSet

#Generate the list of available species and assemblies from the database.
seq_set_obj = SequenceSet.objects.values_list('tax_id', 'assembly').distinct().order_by('tax_id', 'assembly')
SPECIES_ASSEMBLY_CHOICES = [(tax_id+'-'+assembly, tax_id+' - '+assembly) for tax_id, assembly in reversed(seq_set_obj)]
sample_file_path = "hasher/sample_input.gtf"


class HashMapForm(forms.Form):

    text_input = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'placeholder': open('hasher/directions.html').read()})
    )

    species_assembly = forms.ChoiceField(
        required=True,
        initial=SPECIES_ASSEMBLY_CHOICES[0][0],
        choices=SPECIES_ASSEMBLY_CHOICES,
    )

webtool/ugahash/hasher/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext, loader
from .forms import HashMapForm
from ugahash.resources import HashMapHasher
from ugahash.resources.CrossMap import map_coordinates
from ugahash import settings
import csv
from .models import Sequence, SequenceSet, ParentChildSeqRelations, SequenceSetSequenceRelation
import json


def generategtfs(gtf_lines, species, assembly):
    """ Yields data parsed from GTF/GFF files.

    :param gtf_lines: A set of GTF/GFF formatted lines.
    :param species: A tax id the gtf_lines are from.
    :param assembly: The assembly version the gtf_lines are from.
    :return: Yields parsed GTF/GFF data.
    """
    exon_bound_list = []
    prev_seq_type = None
    prev_chromosome = None
    prev_start = None
    prev_stop = None
    prev_frame = None
    prev_strand = None
    prev_something = None

    for line in gtf_lines:
        spln = line.split()

        chromosome = spln[0]
        source  = spln[1]
        seq_type = spln[2]
        start = spln[3]
        stop = spln[4]
        frame = spln[5]
        strand = spln[6]
        something = spln[7]

        if seq_type == "gene":

            if not exon_bound_list == []:
                exon_bound_list = sorted(exon_bound_list)
                hashed_ac = HashMapHasher.UGAHash(
                    prev_seq_type[0].upper(),
                    assembly,
                    prev_chromosome,
                    prev_strand,
                    exon_bound_list
                )

                yield {
                       "seq_type": prev_seq_type,
                       "chromosome": prev_chromosome,
                       "strand": strand,
                       "exon_bound_list": exon_bound_list
                       }

                exon_bound_list = []

            yield {
                   "seq_type": seq_type,
                   "chromosome": chromosome,
                   "strand": strand,
                   "exon_bound_list": ((start, stop),)
            }

        elif seq_type == "transcript":

            if not exon_bound_list == []:
                exon_bound_list = sorted(exon_bound_list)

                yield {
                    # "hashed_ac": hashed_ac,
                    "seq_type": prev_seq_type,
                    "chromosome": prev_chromosome,
                    "strand": strand,
                    "exon_bound_list": exon_bound_list,
                }
                exon_bound_list = []

            prev_seq_type = seq_type
            prev_chromosome = chromosome
            prev_start = start
            prev_stop = stop
            prev_strand = strand
            prev_something = something

        elif seq_type == "exon":
            exon_bound_list.append((int(start), int(stop)))

            yield {
                   "seq_type": seq_type,
                   "chromosome": chromosome,
                   "strand": strand,
                   "exon_bound_list": ((start, stop),)
            }

        else:
            yield {
                   "seq_type": seq_type,
                   "chromosome": chromosome,
                   "strand": strand,
                   "exon_bound_list": ((start, stop),)
            }

    exon_bound_list = sorted(exon_bound_list)

    if exon_bound_list:
        yield {
            "seq_type": prev_seq_type,
            "chromosome": prev_chromosome,
            "strand": strand,
            "exon_bound_list": exon_bound_list

        }


def hashactotype(hash_id):

    if "UG_" == hash_id[:3]:
        return "gene"
    elif "UT_" == hash_id[:3]:
        return "transcript"
    elif "UE_" == hash_id[:3]:
        return "exon"
    else:
        return False


def getsequencetype(hash_id):
    if hash_id[1] == "G":
        return 'gene'
    elif hash_id[1] == "T":
        return 'transcript'
    elif hash_id[1] == "E":
        return 'exon'
    else:
        assert False


def getrevervedseqtype(sequence_type):
    if sequence_type.lower() == "gene":
        return "G"
    elif sequence_type.lower() == "transcript":
        return "T"
    elif sequence_type.lower() == "exon":
        return "E"
    return sequence_type


def resolvefileortext(input_text, file_input_key, request):
    """
    :param input_text:
    :param file_input_key:
    :param request:
    :return:
    """
    error_message = ""
    if input_text == "":
        if file_input_key in request.FILES:
            input_text = request.FILES[file_input_key].read()
        else:
            error_message = "Must submit file or text. No data submitted."
    else:
        if file_input_key in request.FILES:
            error_message = "Must submit file or text. Cannot accept both."
    return input_text, error_message


def existencestate(hashed_ac, source, tax_id, assembly, chromosome, strand, start, stop, seq_type):

    match_exists = SequenceSet.objects.filter(
                sequencesetsequencerelation__hash_id=hashed_ac,
                source=source).exists()

    if not match_exists:
        # Check for overlap.
        start, stop = int(start), int(stop)
        total_len = int((stop - start)*0.25)

        for map_tree_assembly in settings.CHAIN_FILE_DICT[tax_id]:

            use_assembly = assembly
            use_start = start
            use_stop = stop

            if map_tree_assembly != assembly:

                mapped_coordinates = map_coordinates(
                    settings.CHAIN_FILE_DICT[tax_id][assembly][map_tree_assembly],
                    'chr'+chromosome,
                    int(start),
                    int(stop),
                    strand
                )

                try:
                    use_start, use_stop = sorted([mapped_coordinates[-1][1], mapped_coordinates[-1][2]])
                except (ValueError, IndexError):
                    use_start, use_stop = None, None

                use_assembly = map_tree_assembly

            if use_start and use_stop:

                overlap_exists = Sequence.objects.filter(
                    tax_id=tax_id,
                    assembly=use_assembly,
                    chromosome=chromosome,
                    strand=strand,
                    seqsetrels__source=source,
                    seq_type=seq_type,
                    start__range=[start - total_len, start + total_len],
                    stop__range=[stop - total_len, stop + total_len]
                ).exclude(hash_id=hashed_ac).exists()

                if overlap_exists:
                    # Add maybe.
                    match_exists = "overlap"

    return str(match_exists)


def getversionsdict():

    versions_sources = SequenceSet.objects.values_list('source', 'source_version_id').distinct()
    source_dict = {}
    for tup_el in versions_sources:

        source, version = tup_el
        if source not in source_dict:
            source_dict[source] = []

        source_dict[source].append(version)

    return source_dict


def generateboundlist(exon_bound_list, hashed_ac, tax_id, seq_type, assembly, ugahash_args):

    bound_list = []
    prev_start, prev_stop = None, None
    for start, stop in exon_bound_list:
        tmp_start, tmp_stop = sorted([int(start), int(stop)])
        assert ((prev_start is None or prev_start < tmp_start) and (prev_stop is None or prev_stop < tmp_stop))
        bound_list.append(str(tmp_start) + "-" + str(tmp_stop))
        prev_start, prev_stop = tmp_start, tmp_stop

    """%(hash_ac)s?tax_id=%(tax_id)s&sequence_type=%(seq_type)s&assembly=%(assembly)s&chromosome=%(chromosome)s"""

    hash_link = (hashed_ac+"?" +
                 "tax_id=" + tax_id +
                 "&sequence_type=" + seq_type +
                 "&assembly=" + assembly +
                 "&chromosome=" + ugahash_args["chromosome"] +
                 "&strand=" + ugahash_args["strand"].replace("+", "%2B") +
                 "&bounds=" + ":".join(bound_list))

    return hash_link


def index(request):
    """

    :param request:
    :return:
    """

    if request.method == 'GET' and request.GET != {}:

        form = HashMapForm(request.GET, request.FILES)

        if form.is_valid():
            # Get text input.
            text_input, error_message = resolvefileortext(form.cleaned_data['text_input'], 'file_input', request)
            # Get species and assembly.
            tax_id, assembly = form.cleaned_data['species_assembly'].split("-")
            # Get list of distinct sources.
            distinct_sources = sorted(SequenceSet.objects.values_list('source', flat=True).distinct())

            source_dict = sorted(getversionsdict())

            # Iterate over the GFF annotations.
            hashed_seqs = []
            tsv_hashed_seqs = []
            json_hashed_seqs = []
            try:
                for ugahash_args in generategtfs(text_input.strip().split("\n"), tax_id, assembly):

                    seq_type = ugahash_args["seq_type"]
                    chromosome = ugahash_args["chromosome"].strip("chr")
                    strand = ugahash_args["strand"]
                    exon_bound_list = ugahash_args["exon_bound_list"]
                    start = exon_bound_list[0][0]
                    stop = exon_bound_list[-1][-1]

                    # Generate UGA
                    hashed_ac = HashMapHasher.UGAHash(
                        getrevervedseqtype(seq_type),  # Return the tag for the type of feature being hashed.
                        assembly,
                        chromosome,
                        strand,
                        exon_bound_list
                    )

                    # Add basic information for output page.
                    tmp_hashed_seqs = {
                        "hash_id": hashed_ac,
                        "hash_id_link": generateboundlist(
                            exon_bound_list, hashed_ac, tax_id, seq_type, assembly, ugahash_args),
                        "seq_type": seq_type,

webtool/ugahash/hasher/templates/hasher/directions.html
Add GTF or GFF formatted genomic coordinates here.

webtool/ugahash/hasher/templates/hasher/hashmapped.html
{% extends "ugahash/base.html" %}

{% block title %}Hashed Results{% endblock %}

{% block content %}

<style>
    table {
        width: 100%;
    }
   .htitle {
        font-size: 60%;
    }
</style>


<table>
    <tr>
        <th class="htitle">Sequence Hash</th>
        <th class="htitle">Type</th>
        <th class="htitle">Chr</th>
        <th class="htitle">Strand</th>
        <th class="htitle">Start</th>
        <th class="htitle">Stop</th>
        {% for source in distinct_sources %}
           <th class="htitle">{{ source }}</th>
        {% endfor %}
    </tr>
    {% for seq_el in hashed_seqs %}
        <tr>
            <td class="htitle"><a href="sequence/{{ seq_el.hash_id_link }}">{{ seq_el.hash_id }}</a></td>
            <td class="htitle">{{ seq_el.seq_type }}</td>
            <td class="htitle">{{ seq_el.chromosome }}</td>
            <td class="htitle">{{ seq_el.strand }}</td>
            <td class="htitle">{{ seq_el.start }}</td>
            <td class="htitle">{{ seq_el.stop }}</td>

            {% for info_el in seq_el.existences|dictsort:"source"  %}
                <td>
                {% if info_el.existence_state == "True" %}
                    <img style="height: 20px;" src="/static/ugahash/img/match.svg"/>
                {% elif info_el.existence_state == "overlap" %}
                    <img style="height: 20px;" src="/static/ugahash/img/overlap.svg"/>
                {% elif info_el.existence_state == "False" %}
                    <img style="height: 20px;" src="/static/ugahash/img/mismatch.svg"/>
                {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>

{% endblock %}

webtool/ugahash/hasher/templates/hasher/index.html
{% extends "ugahash/base.html" %}

{% block title %}Hash{% endblock %}

{% block content %}

    <script>
        $(document).ready(function(){
        $("#load_sample_data").click(function(){
                $("#id_text_input").load("/static/ugahash/data/sample.gtf.html");
            }
        );
    });
    </script>


    <form action="/hash/" method="get">


        {{ form.non_field_errors }}
        <div class="fieldWrapper">

        {{ form.text_input.errors }}
        {{ form.text_input }}
        <a id="load_sample_data" style=" font-size:85%; float: right; margin-top: -10px;"  >
            [Load Sample Data]
        </a>
        </div>

        <div class="fieldWrapper">
        {{ form.message.errors }}
        <label for="{{ form.message.id_for_label }}">Species and Version of Assembly:</label>
        {{ form.species_assembly }}
        </div>


        <input type="submit" value="Submit" />
    </form>

    {% if error_message %}
        <strong style="color: red">{{ error_message }}</strong>
    {% endif %}


    {% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
    {% endif %}


{% endblock %}

webtool/ugahash/hasher/templates/hasher/sequence_page.html
{% extends "ugahash/base.html" %}

{% block title %}{{ job_id }}{% endblock %}

{% block content %}

<style>
    table {
        width: 100%;
    }
</style>

<h5>Sequence Info</h5>
<table>
    <tr>
        <th colspan="1">UGA</th>
        <td colspan="5">{{ job_id }}</td>
    </tr>
    <tr>
        <th> Species</th>
        <th> Assembly</th>
        <th> Chromosome</th>
        <th> Strand</th>
        <th> Start</th>
        <th> End</th>
    </tr>
    <tr>
        <td>{{ tax_id }}</td>
        <td>{{ assembly }}</td>
        <td>{{ chromosome }}</td>
        <td>{{ strand }}</td>
        <td>{{ start }}</td>
        <td>{{ stop }}</td>
    </tr>
</table>

<h5>External Database Relations</h5>
<table>
        <tr>
            <th>Source</th>
            <th>Version</th>
            <th>Accession in Database</th>
        </tr>
    {% if links_to_DBs %}
        {% for source, version, original_id, source_url in links_to_DBs %}
            <tr>
                <td>{{ source }}</td>
                <td>{{ version }}</td>
                <td> <a target="_blank" href="{{ source_url }}">{{ original_id }}</a></td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="3">None</td>
        </tr>
    {% endif %}
</table>


<h5>Parent Sequences</h5>
<table>
        <tr>
            <th>UGA</th>
            <th>Sequence Type</th>
            <th>Start</th>
            <th>Stop</th>
        </tr>
        {% if parents %}
        {% for hash_id, assembly, seq_type, chromosome, strand, start, stop in parents %}
            <tr>
                <td><a href="/hash/sequence/{{ hash_id }}">{{ hash_id }}</a></td>
                <td>{{ seq_type }}</td>
                <td>{{ start }}   </td>
                <td>{{ stop }}    </td>
            </tr>
        {% endfor %}
    {% else %}
    <tr>
        <td colspan="4">None</td>
    </tr>
{% endif %}
</table>

<h5>Child Sequences</h5>
<table>
        <tr>
            <th>UGA</th>
            <th>Sequence Type</th>
            <th>Start</th>
            <th>Stop</th>
        </tr>
{% if children %}
    {% for hash_id, assembly, seq_type, chromosome, strand, start, stop in children %}
        <tr>
            <td><a href="/hash/sequence/{{ hash_id }}">{{ hash_id }}</a></td>
            <td>{{ seq_type }}</td>
            <td>{{ start }}</td>
            <td>{{ stop }}</td>
        </tr>
    {% endfor %}
{% else %}
    <tr>
        <td colspan="4">None</td>
    </tr>
{% endif %}
</table>


<h5>Related Sequences</h5>
<table>
    <tr>
        <th>Hash ID</th>
        <th>Assembly</th>
        <th>Position</th>
        <th>Source & Version</th>
        <th>Original ID</th>
    </tr>
    {% if grouped_data_struct %}
        {% for hash_id, vals in grouped_data_struct.items %}
            <tr>
                <td rowspan="{{ vals.origin_data|length|add:1 }}">
                    <a href="/hash/sequence/{{ hash_id }}">{{ hash_id }}</a>
                </td>
                <td rowspan="{{ vals.origin_data|length|add:1 }}">
                    {{ vals.assembly }}
                </td>
                <td rowspan="{{ vals.origin_data|length|add:1 }}">
                    {{ vals.chromosome }}{{ vals.strand }}:{{ vals.start }}-{{ vals.stop }}
                </td>
            </tr>
            {% for vers in vals.origin_data|dictsort:"version" %}
                <tr>
                    <td>{{ vers.version }}</td>
                    <td>{{ vers.original_id }}</td>
                </tr>
            {% endfor %}

        {% endfor %}
    {% else %}
        <tr>
            <td colspan="6">None</td>
        </tr>
    {% endif %}
</table>


{% endblock %}